application:
  project: protocol

server:
  shutdown: graceful
  #port: 8080
  port: 8090

spring:
  application.name: protocol-${common.blockchain}-nft-order-api
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  main:
    banner-mode: log
    web-application-type: reactive
  data:
    mongodb:
      #uri: mongodb://${mongodb.hosts}
      #database: ${mongodb.database}
      uri: mongodb://admin:123456@10.31.4.41:27017
      database: soundsright-test

  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        service-name: ${common.blockchain}-nft-order-api    

common:
  event-producer:
    environment: ${application.environment}
    kafka-replica-set: ${kafka.hosts}
  blockchain: ethereum
rarible:
  ethereum:
    converter:
      enabled: true
